/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import org.apache.poi.ss.usermodel.*;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Asdrubal Rivas
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RegistrosDeClientes = new javax.swing.JButton();
        BusquedaDeReservacion = new javax.swing.JButton();
        HistorialDeHabitacion = new javax.swing.JButton();
        CheckIn = new javax.swing.JButton();
        CheckOut = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        CargarArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Proyecto 2");

        RegistrosDeClientes.setText("Registro de Clientes");
        RegistrosDeClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrosDeClientesActionPerformed(evt);
            }
        });

        BusquedaDeReservacion.setText("Búsqueda de reservación");
        BusquedaDeReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaDeReservacionActionPerformed(evt);
            }
        });

        HistorialDeHabitacion.setText("Historial de habitación");
        HistorialDeHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialDeHabitacionActionPerformed(evt);
            }
        });

        CheckIn.setText("Check-in");
        CheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInActionPerformed(evt);
            }
        });

        CheckOut.setText("Check-Out");
        CheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CargarArchivo.setText("Cargar Archivo");
        CargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegistrosDeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HistorialDeHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BusquedaDeReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrosDeClientes)
                    .addComponent(BusquedaDeReservacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HistorialDeHabitacion)
                    .addComponent(CheckIn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckOut))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(CargarArchivo)))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void RegistrosDeClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrosDeClientesActionPerformed
        // TODO add your handling code here:
        dispose();
        Registrar register = new Registrar();
        register.setLocationRelativeTo(null);
        register.setSize(600, 400);
        register.setResizable(false);
        register.setTitle("Registrar Clientes");
        register.setVisible(true);
    }//GEN-LAST:event_RegistrosDeClientesActionPerformed

    public void BusquedaDeReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaDeReservacionActionPerformed
        // TODO add your handling code here:
        dispose();
        BusquedaDeReserva BusquedaReservacion = new BusquedaDeReserva();
        BusquedaReservacion.setLocationRelativeTo(null);
        BusquedaReservacion.setSize(600, 400);
        BusquedaReservacion.setResizable(false);
        BusquedaReservacion.setTitle("Busqueda De Reversacion");
        BusquedaReservacion.setVisible(true);
    }//GEN-LAST:event_BusquedaDeReservacionActionPerformed

    public void HistorialDeHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialDeHabitacionActionPerformed
        // TODO add your handling code here:
        dispose();
        HistorialDeHabitacion historialdehabitacion = new HistorialDeHabitacion();
        historialdehabitacion.setLocationRelativeTo(null);
        historialdehabitacion.setSize(600, 400);
        historialdehabitacion.setResizable(false);
        historialdehabitacion.setTitle("Historial de Habitacion");
        historialdehabitacion.setVisible(true);
        
    }//GEN-LAST:event_HistorialDeHabitacionActionPerformed

    public void CheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInActionPerformed
        // TODO add your handling code here:
        dispose();
        Check_In checkin = new Check_In();
        checkin.setLocationRelativeTo(null);
        checkin.setSize(600, 400);
        checkin.setResizable(false);
        checkin.setTitle("Check-In");
        checkin.setVisible(true);
    }//GEN-LAST:event_CheckInActionPerformed

    public void CheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutActionPerformed
        // TODO add your handling code here:
        dispose();
        Checkout chekis = new Checkout();
        chekis.setLocationRelativeTo(null);
        chekis.setSize(600, 400);
        chekis.setResizable(false);
        chekis.setTitle("Check-Out");
        chekis.setVisible(true);
    }//GEN-LAST:event_CheckOutActionPerformed

    public void CargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();

        // Establecer el filtro de extensión para mostrar solo archivos de Excel
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de Excel", "xls", "xlsx");
        fileChooser.setFileFilter(filter);

        // Mostrar el cuadro de diálogo
        int result = fileChooser.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            // Obtener el archivo seleccionado
            File selectedFile = fileChooser.getSelectedFile();

            // Cargar el archivo de Excel
            try {
                cargarArchivoExcel(selectedFile);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    public static void cargarArchivoExcel(File file) throws IOException {
        FileInputStream fileInputStream = new FileInputStream(file);
        Workbook workbook = WorkbookFactory.create(fileInputStream);

        // Obtener la primera hoja del archivo
        Sheet sheet = workbook.getSheetAt(0);

        // Iterar sobre las filas y columnas de la hoja
        for (Row row : sheet) {
            for (Cell cell : row) {
                // Obtener el valor de la celda
                String cellValue = cell.toString();
                System.out.print(cellValue + "\t");
            }
            System.out.println();
        }

        // Cerrar el FileInputStream
        fileInputStream.close();
    
    
    
        


    
    

        
        
    }//GEN-LAST:event_CargarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BusquedaDeReservacion;
    public javax.swing.JButton CargarArchivo;
    public javax.swing.JButton CheckIn;
    public javax.swing.JButton CheckOut;
    public javax.swing.JButton HistorialDeHabitacion;
    public javax.swing.JButton RegistrosDeClientes;
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
